### ISSUE TITLE
Broken in pelican 

### ISSUE THREAD

**Issue by m3nu** [joachimneu/pelican-md-metayaml#10]
The `MarkdownReader` class may have changed. With pelican `3.7.1` I get the following error on startup:

```
DEBUG: Pelican version: 3.7.1
DEBUG: Python version: 3.5.2
WARNING: JINJA_EXTENSIONS setting has been deprecated, moving it to JINJA_ENVIRONMENT setting.
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `i18n_subsites`
DEBUG: Registering plugin `i18n_subsites`
DEBUG: Loading plugin `pelican-md-metayaml`
DEBUG: Registering plugin `pelican-md-metayaml`
DEBUG: Restoring system path
CRITICAL: AttributeError: 'NoneType' object has no attribute 'append'
Traceback (most recent call last):
  File "/Users/manu/.pyenv/versions/miniconda3-4.1.11/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/Users/manu/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/pelican/__init__.py", line 394, in main
    readers = Readers(settings)
  File "/Users/manu/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/pelican/readers.py", line 471, in __init__
    self.readers[fmt] = reader_class(self.settings)
  File "/Users/manu/Workspace/chalet-valerie/3rd-party-plugins/pelican-md-metayaml/md_metayaml.py", line 11, in __init__
    self.extensions.append(MetaYamlExtension())
AttributeError: 'NoneType' object has no attribute 'append'
```

Setting `self.extensions` to an empty list `[]` initially fixes it. I'm not 100% sure if this is a good solution though.

```
    def __init__(self, *args, **kwargs):
        super(MarkdownYAMLReader, self).__init__(*args, **kwargs)
        self.extensions = []
        self.extensions.append(MetaYamlExtension())
```

**Comment by vhotspur** [comment]
I would say that the correct fix is to replace the line with:

```python
self.settings['MARKDOWN']['extensions'].append(MetaYamlExtension())
```

**Comment by m3nu** [comment]
Awesome. Wanna do a PR? I'll do it, if it gets merged, @joachimneu ?

**Comment by joachimneu** [comment]
Sure, I will merge PRs if they are tested.

**Comment by vhotspur** [comment]
@joachimneu by tested you mean "it works for me while without the patch it failed with an exception" or there is somewhere a test suite where it can be added?

By the way, I think I found that it is broken since [this commit](https://github.com/getpelican/pelican/commit/35dba138e0b3dc0f3ff58eae413f059ab68f57b3) that changed how extensions are stored within a `MarkdownReader`.

**Comment by m3nu** [comment]
Created PR #11 and tested with latest Pelican version. Works again as expected.
